2016-03-23 18:05:25,286 ERROR o.g.v.c.b.MultipleBatchAnalysis [main] Problem working this image:/mnt/sdb1/SumoImgs/S1/artic/EW/S1A_EW_GRDM_1SDH_20150323T105843_20150323T105943_005158_006809_CBF7.SAFE/manifest.safe
java.lang.NullPointerException
	at org.geoimage.viewer.core.io.SumoXMLWriter.saveNewXML(SumoXMLWriter.java:376) ~[classes/:?]
	at org.geoimage.viewer.core.batch.AbstractBatchAnalysis.saveResults(AbstractBatchAnalysis.java:221) ~[classes/:?]
	at org.geoimage.viewer.core.batch.MultipleBatchAnalysis.runAnalysis(MultipleBatchAnalysis.java:173) [classes/:?]
	at org.geoimage.viewer.core.batch.AbstractBatchAnalysis.runProcess(AbstractBatchAnalysis.java:79) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.execAnalysis(Sumo.java:74) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.main(Sumo.java:212) [classes/:?]
2016-03-23 18:06:30,229 ERROR o.g.v.c.b.MultipleBatchAnalysis [main] Problem working this image:/mnt/sdb1/SumoImgs/S1/artic/EW/S1A_EW_GRDM_1SDH_20160130T050441_20160130T050546_009719_00E30C_0996.SAFE/manifest.safe
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@365c11f0 rejected from java.util.concurrent.ThreadPoolExecutor@27e97fd8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_65]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_65]
	at org.geoimage.viewer.core.batch.MultipleBatchAnalysis.runAnalysis(MultipleBatchAnalysis.java:163) [classes/:?]
	at org.geoimage.viewer.core.batch.AbstractBatchAnalysis.runProcess(AbstractBatchAnalysis.java:79) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.execAnalysis(Sumo.java:74) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.main(Sumo.java:212) [classes/:?]
2016-03-23 18:07:01,616 ERROR o.g.v.c.b.MultipleBatchAnalysis [main] Problem working this image:/mnt/sdb1/SumoImgs/S1/artic/EW/S1A_EW_GRDM_1SDH_20160201T012818_20160201T012918_009746_00E3DC_E2B3.SAFE/manifest.safe
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4b97399f rejected from java.util.concurrent.ThreadPoolExecutor@27e97fd8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_65]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_65]
	at org.geoimage.viewer.core.batch.MultipleBatchAnalysis.runAnalysis(MultipleBatchAnalysis.java:163) [classes/:?]
	at org.geoimage.viewer.core.batch.AbstractBatchAnalysis.runProcess(AbstractBatchAnalysis.java:79) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.execAnalysis(Sumo.java:74) [classes/:?]
	at org.geoimage.viewer.core.batch.Sumo.main(Sumo.java:212) [classes/:?]
